const documents = [];
let activeView = 'all'; let uploaded = []; let activeDocument = null;
const allowedPasswords = ['Arsipku2024!', 'Viewer#248', 'Raka@Admin'];
const $ = s => document.querySelector(s); const rows = $('#documentRows');
function render() { let q = $('#searchInput').value.toLowerCase(); let list = [...documents, ...uploaded].filter(d => (activeView === 'all' || activeView === 'recent' || (activeView === 'favorites' && d.favorite) || (activeView === 'shared' && d.owner !== 'Anda')) && [d.name, d.owner, d.folder].join(' ').toLowerCase().includes(q)); const sort = $('#sortSelect').value; if (sort === 'name') list.sort((a, b) => a.name.localeCompare(b.name)); if (sort === 'size') list.sort((a, b) => parseFloat(a.size) - parseFloat(b.size)); if (sort === 'updated') list.sort((a, b) => a.time - b.time); rows.innerHTML = list.map((d, i) => `<tr><td><input type="checkbox" aria-label="Pilih ${d.name}"></td><td><div class="document-name" data-index="${documents.indexOf(d)}" data-upload="${uploaded.indexOf(d)}"><span class="file-icon ${d.type === 'DOC' ? 'doc' : d.type === 'XLS' ? 'xls' : ''}">${d.type}</span>${d.name}</div></td><td><div class="owner"><span class="owner-avatar ${d.avatar}">${d.initials}</span>${d.owner}</div></td><td class="muted">${d.updated}</td><td class="muted">${d.size}</td><td><button class="more" aria-label="Opsi ${d.name}">•••</button></td></tr>`).join(''); $('#resultCount').textContent = list.length; $('#showingCount').textContent = list.length; $('.card-heading p').firstElementChild?.classList?.remove('x'); }
function toast(msg) { const t = $('#toast'); t.textContent = msg; t.classList.add('show'); setTimeout(() => t.classList.remove('show'), 2500) }
function openViewer(d) { activeDocument = d; $('#modalIcon').textContent = 'PDF'; $('#modalIcon').className = 'file-icon large'; $('#modalTitle').textContent = d.name; $('#modalMeta').textContent = `${d.size}  ·  Diubah ${d.updated}`; $('#previewHeading').textContent = d.name.replace(/\.[^.]+$/, ''); $('#passwordGate').classList.remove('unlocked'); document.querySelectorAll('.protected-content').forEach(el => el.classList.remove('unlocked')); $('#documentPassword').value = ''; $('#passwordError').textContent = ''; $('#viewerModal').classList.add('open'); setTimeout(() => $('#documentPassword').focus(), 50) }
$('#searchInput').addEventListener('input', render); $('#sortSelect').addEventListener('change', render); rows.addEventListener('click', e => { const target = e.target.closest('.document-name'); if (target) { let d = target.dataset.upload > -1 ? uploaded[target.dataset.upload] : documents[target.dataset.index]; openViewer(d) } });
document.querySelectorAll('.nav-item').forEach(btn => btn.addEventListener('click', () => { document.querySelectorAll('.nav-item').forEach(x => x.classList.remove('active')); btn.classList.add('active'); activeView = btn.dataset.view; $('#documentTitle').textContent = btn.textContent.trim().replace(/\d+$/, ''); render() }));
$('#uploadTrigger').addEventListener('click', () => $('#fileInput').click()); $('#fileInput').addEventListener('change', e => { [...e.target.files].forEach((f, i) => uploaded.push({ name: f.name, type: f.name.split('.').pop().toUpperCase().slice(0, 3), owner: 'Anda', initials: 'RA', updated: 'Baru saja', time: 0, size: `${Math.max(1, Math.round(f.size / 1024))} KB`, folder: 'Administrasi' })); if (e.target.files.length) { toast(`${e.target.files.length} dokumen berhasil ditambahkan`); render() } });
$('#closeModal').addEventListener('click', () => $('#viewerModal').classList.remove('open')); $('#viewerModal').addEventListener('click', e => { if (e.target.id === 'viewerModal') $('#viewerModal').classList.remove('open') }); $('#passwordForm').addEventListener('submit', e => { e.preventDefault(); if (allowedPasswords.includes($('#documentPassword').value)) { $('#passwordGate').classList.add('unlocked'); document.querySelectorAll('.protected-content').forEach(el => el.classList.add('unlocked')); toast('Akses diberikan — mode hanya lihat aktif') } else { $('#passwordError').textContent = 'Kata sandi tidak valid atau tidak memiliki izin akses.'; $('#documentPassword').select() } }); $('#togglePassword').addEventListener('click', () => { const input = $('#documentPassword'); input.type = input.type === 'password' ? 'text' : 'password' }); document.addEventListener('copy', e => { if ($('#viewerModal').classList.contains('open') && document.querySelector('.protected-content.unlocked')) { e.preventDefault(); toast('Penyalinan dokumen dibatasi') } }); document.addEventListener('contextmenu', e => { if ($('#viewerModal').classList.contains('open')) { e.preventDefault(); toast('Klik kanan dinonaktifkan pada viewer') } }); $('#filterButton').addEventListener('click', () => { toast('Filter lanjutan siap digunakan'); $('#filterButton').classList.toggle('filtered'); $('#filterBadge').textContent = '1' }); $('#addFolder').addEventListener('click', () => toast('Folder baru siap dibuat')); document.querySelectorAll('.pagination button:not(:disabled)').forEach(b => b.addEventListener('click', () => toast('Halaman dokumen diperbarui'))); render();

const loginAccounts = {
  'admin@arsipku.id': { password: 'Arsipku2024!', name: 'Raka Aditya', initials: 'RA', role: 'Administrator' },
  'rani@arsipku.id': { password: 'Viewer#248', name: 'Rani Kusuma', initials: 'RK', role: 'Editor' },
  'dimas@arsipku.id': { password: 'Raka@Admin', name: 'Dimas Pratama', initials: 'DP', role: 'Viewer' }
};
function applyUser(user) { $('#profileName').textContent = user.name; $('#profileRole').textContent = user.role; $('.profile .avatar').textContent = user.initials; $('#welcomeText').textContent = `SELAMAT DATANG KEMBALI, ${user.name.split(' ')[0].toUpperCase()}`; }
function showApp(user) { applyUser(user); $('#loginScreen').style.display = 'none'; $('#appShell').classList.add('authenticated'); }
$('#loginForm').addEventListener('submit', e => { e.preventDefault(); const email = $('#loginEmail').value.trim().toLowerCase(); const password = $('#loginPassword').value; const user = loginAccounts[email]; if (!user || user.password !== password) { $('#loginError').textContent = 'Email atau kata sandi tidak sesuai.'; return } if ($('#rememberLogin').checked) localStorage.setItem('arsipkuUser', email); showApp(user); toast(`Selamat datang, ${user.name}`); });
$('#toggleLoginPassword').addEventListener('click', () => { const input = $('#loginPassword'); input.type = input.type === 'password' ? 'text' : 'password' }); $('#forgotPassword').addEventListener('click', e => { e.preventDefault(); $('#loginError').textContent = 'Hubungi administrator untuk mengatur ulang kata sandi.' }); $('#logoutButton').addEventListener('click', () => { localStorage.removeItem('arsipkuUser'); $('#appShell').classList.remove('authenticated'); $('#appShell').style.display = 'none'; $('#loginScreen').style.display = 'grid'; $('#loginPassword').value = ''; toast('Anda telah keluar dari sistem') });
const rememberedUser = localStorage.getItem('arsipkuUser'); if (rememberedUser && loginAccounts[rememberedUser]) showApp(loginAccounts[rememberedUser]);
